### PR TITLE
Fixes react-native-maps collisions

### PR DESCRIPTION
**Pull request by cesartotvs**
onSelect event is colliding with react-native-maps, to prevent the collision onSelect has be changed to onChartSelect.

### CODE REVIEW

**Comment by cesartotvs** [comment]
@wuxudong Can you please review this pull request.

**Comment by cesartotvs** [comment]
@wuxudong Bump

**Comment by wuxudong** [comment]
Will two same name function collide even they belong to two different container (Chart and Map) ?

**Comment by hungdev** [comment]
@wuxudongI think this pull request should be merged. I have encountered this error and I have to fork your repository.
https://github.com/hungdev/react-native-charts-wrapper

**Comment by cesartotvs** [comment]
@wuxudong Friendly bump.

**Comment by wuxudong** [comment]
I found a better way to handle the collision of onSelect with react-native-maps.

But there is still a problem to use it with react-native-maps.

After merging #343 ,  Podfile looks like this:

    use_frameworks!

    target '_YOUR_TARGET_NAME_' do
        ......
        pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
    end

but `use_frameworks!` will cause problem if you also add react-native-maps to Podfile.

    rn_path = '../node_modules/react-native'
    rn_maps_path = '../node_modules/react-native-maps'

    pod 'react-native-maps', path: rn_maps_path
    pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
    pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
    pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS

I tried to add both react-native-charts-wrapper and react-native-maps to Podfile, but failed.

But at least, you can add react-native-charts-wrapper manually like before.

**Pull request closed without merging**
