### PR TITLE
Gradient support for line chart android.

### PR DESCRIPTION
**Pull request by DeepakSena**

### CODE REVIEW

**Comment by Dineshchitta** [comment]
@wuxudong Is there gradient support for line chart ?

**Comment by wuxudong** [comment]
Charts do not support this feature currently. check [this](https://github.com/danielgindi/Charts/issues/537)

**Comment by wuxudong** [comment]
Charts do not support this feature currently. 
Check [this](https://github.com/danielgindi/Charts/issues/537).

I haven't test the android pull request yet. I will make a try.

**Comment by Dineshchitta** [comment]
@wuxudong Thanks for the quick reply. you are saying gradient is not supported for line color and fill color as well right ?

**Comment by wuxudong** [comment]
Yes, not supported yet.

**Pull request closed without merging**
